[general]
import = [
    "themes/dracula.toml"
]

[terminal]
shell = "zsh"

[window]
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 0.8
blur = true

[font]
size = 12
normal = { family = "0xProto Nerd Font Mono", style = "Regular"}
bold = { family = "0xProto Nerd Font Mono", style = "Bold"}
italic = { family = "0xProto Nerd Font Mono", style = "Italic"}
bold_italic = { family = "0xProto Nerd Font Mono", style = "Bold Italic"}
