require("core.keymaps")
require("core.options")
require("core.autocmds")

require("plugins.colors")
require("plugins.lsp")
require("plugins.diagnostics")

require("plugins.barbar")
require("plugins.colorize")
require("plugins.fugitive")
require("plugins.hover")
require("plugins.kulala")
require("plugins.lualine")
require("plugins.markdown")
require("plugins.nvimtreedevicons")
require("plugins.snippets")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.undotree")
require("plugins.trouble")
